# Generated by Django 5.2.17 on 2026-09-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('level', models.CharField(choices=[('campus', 'Campus'), ('national', 'National'), ('international', 'International')], default='campus', max_length=255)),
                ('achieved_at', models.DateField()),
            ],
        ),
    ]
