# Generated by Django 5.2.17 on 2026-09-22 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_achievement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='title',
        ),
    ]
